#!/usr/bin/env bash

export DOTFILES=$(cd -P -- $(dirname -- $BASH_SOURCE[0]) && pwd -P)
unix_name=$(uname)

is_installed() {
    command -v "$1" >/dev/null
}

if [ $unix_name == "Darwin" ]; then
    if ! is_installed brew; then
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew tap "homebrew/cask"
        brew tap "homebrew/core"
        brew tap "homebrew/services"
    fi
    installer="brew"
elif [ $unix_name == "Linux" ]; then
    if is_installed yum; then
        installer="yum -y"
    elif is_installed apt-get; then
        installer="apt-get -y"
    fi
else
    echo "Something unexpected happened"
    exit 1
fi

# Install with package manager
while read package; do
    if ! is_installed $package; then
        $installer install $package
    fi
done < $DOTFILES/config/packages

# Custom installers
for installer in $DOTFILES/installers/*; do
    if [ -x $installer ]; then
        $installer
    fi
done

while read dotfile; do
    stow --verbose --restow --dir=$DOTFILES/files --target=$HOME $dotfile
done < $DOTFILES/config/dotfiles
