#!/usr/bin/env bash

export DOTFILES=$(cd -P -- $(dirname -- $BASH_SOURCE[0]) && pwd -P)
unix_name=$(uname)

for helper in $DOTFILES/helpers/*; do
    source $helper
done

if [ $unix_name == "Darwin" ]; then
    if ! is_installed brew; then
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew tap "homebrew/core"
        brew tap "homebrew/services"
    fi
    installer="brew"
elif [ $unix_name == "Linux" ]; then
    if is_installed yum; then
        installer="sudo yum -y"
    elif is_installed apt-get; then
        installer="sudo apt-get -y"
    fi
else
    echo "Something unexpected happened"
    exit 1
fi

# Install with package manager
while read package; do
    if ! is_installed $package; then
        $installer install $package
    fi
done < $DOTFILES/config/packages

# Custom installers
for installer in $DOTFILES/installers/*; do
    if [ -x $installer ] && [ ! -d $installer ]; then
        $installer
    fi
done

# OS-specific custom installers
if [ -d $DOTFILES/installers/$unix_name ]; then
    for installer in $DOTFILES/installers/$unix_name/*; do
        if [ -x $installer ]; then
            $installer
        fi
    done
fi

while read dotfile; do
    attempt_stow $HOME $dotfile
done < $DOTFILES/config/dotfiles

# macOS Application Support
if [ $unix_name == "Darwin" ]; then
    while read file; do
        attempt_stow "$HOME/Library/Application Support" $file
    done < $DOTFILES/config/Darwin/library
fi
