#!/usr/bin/env bash

base_path=$(cd -P -- $(dirname -- $BASH_SOURCE[0]) && pwd -P)

./install

while read dotfile; do
    stow --verbose --restow --dir="$base_path/files" --target=$HOME $dotfile
done < "$base_path/config/dotfiles"
