#!/usr/bin/env bash

# Better colors and italics
rm -rf $HOME/.terminfo
tic -o $HOME/.terminfo terminfo/xterm-256color.terminfo
tic -o $HOME/.terminfo terminfo/tmux-256color.terminfo
tic -o $HOME/.terminfo terminfo/tmux.terminfo

# Set vars for context
if type nvim > /dev/null; then
    vimdir=$HOME/.local/share/nvim
    vimfilepath=$HOME/.config/nvim
    vimfile=$vimfilepath/init.vim
    mkdir -p $vimfilepath
else
    vimdir=$HOME/.vim
    vimfile=$HOME/.vimrc
fi

# Move things into place
rm -rf $vimdir
cp .vimrc $vimfile
cp .tmux.conf $HOME/.tmux.conf
cp .aliases $HOME/.aliases
cp .agignore $HOME/.agignore

if [ -x "$(command -v fish)" ]; then
    mkdir -p $HOME/.config/fish
    cp .config/fish/config.fish $HOME/.config/fish/config.fish
    cp .config/fish/functions/fish_prompt.fish $HOME/.config/fish/functions/fish_prompt.fish
fi

# TODO there must be an easier way
if [[ "$OSTYPE" == "darwin"* ]] && [[ ! -d "${HOME}/Library/Fonts/FiraCode/" ]]; then
    git clone git@github.com:tonsky/FiraCode.git
    rsync -va --delete-after FiraCode/distr/otf/ $HOME/Library/Fonts/FiraCode/
    rm -rf FiraCode
fi

# Music Player Daemon
mkdir -p $HOME/.mpd/playlists
touch $HOME/.mpd/{mpd.db,mpd.log,mpd.pid,mpdstate}
cp .mpd/mpd.conf $HOME/.mpd/mpd.conf

# NCurses Music Player Client (Plus Plus)
mkdir -p $HOME/.ncmpcpp
cp .ncmpcpp/bindings $HOME/.ncmpcpp/bindings
cp .ncmpcpp/config $HOME/.ncmpcpp/config

# Karibiner
# Use to make media keys work for mpc
mkdir -p $HOME/.config/karabiner
cp .config/karabiner/karabiner.json $HOME/.config/karabiner
