#!/usr/bin/env bash

is_installed() {
    brew cask list "$1" > /dev/null 2>&1
}

read -rep "Install cask Applications (y/n) " -n 1

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

while read package; do
    if ! is_installed $package; then
        brew cask install $package
    fi
done < $DOTFILES/config/cask
