#!/usr/bin/env bash

if [ $(uname) != "Darwin" ]; then
    exit 0
fi

is_installed() {
    brew list "$1" > /dev/null 2>&1
}

while read package; do
    if ! is_installed $package; then
        brew install $package
    fi
done < $DOTFILES/config/brew
