#!/usr/bin/env bash

# Better color support for terminfo

# Delete the current compiled file
rm -rf $HOME/.terminfo

# Compile a new file from the source files
tic -o $HOME/.terminfo $DOTFILES/files/terminfo/xterm-256color.terminfo
tic -o $HOME/.terminfo $DOTFILES/files/terminfo/tmux-256color.terminfo
tic -o $HOME/.terminfo $DOTFILES/files/terminfo/tmux.terminfo
