#!/usr/bin/env bash

# Work doesn’t have fish and tho you know
# ur boi loves fish
# I just want one shell to use
# Thusly zsh
# TODO?? chef out fish???
if [ $SHELL != $(which zsh) ]; then
    chsh -s `which zsh`
fi

if [[ ! -d "${HOME}/.oh-my-zsh/" ]]; then
    bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
