#!/usr/bin/env bash

# Install MacOS specific dependencies

base_path=$(dirname $(cd -P -- $(dirname -- $BASH_SOURCE[0]) && pwd -P))

is_installed() {
    command -v "$1" >/dev/null
}

if ! is_installed brew; then
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew bundle --file="$base_path/config/brew-base"
