#!/usr/bin/env bash

# Install Linux specific dependencies

base_path=$(dirname $(cd -P -- $(dirname -- $BASH_SOURCE[0]) && pwd -P))

is_installed() {
    command -v "$1" >/dev/null
}

if is_installed yum; then
    installer=yum
elif is_installed apt-get; then
    installer=apt-get
else
    echo "I am not sure which Linux package manager to use"
    exit 1
fi

$installer -y install $(cat "$base_path/config/packages")
